trigger:
  branches:
trigger:
  branches:
    include:
      - test  # 가져올 브랜치 이름

jobs:
- job: SyncCodeToCentOS
  displayName: 'Sync Code to Azure CentOS 7.9'
  pool:
    vmImage: 'centos-latest'  # 사용할 빌드 에이전트 이미지 선택

  steps:
  - task: AzureCLI@2
    displayName: 'SSH to Azure CentOS 7.9'
    inputs:
      azureSubscription: 'Microsoft 파트너 네트워크'  # 사용할 Azure 구독 이름
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Azure CentOS 7.9에 SSH로 접속
        # SSH 접속 명령어를 적절히 변경해야 합니다.
        ssh user@<centos-ip-address> -i <ssh-private-key-file>

  - task: GitCheckout@2
    displayName: 'Checkout code from Git repository'
    inputs:
      repository: 'https://github.com/cksdud0707/test'  # 가져올 Git 저장소 URL
      clean: true

  - task: CopyFiles@2
    displayName: 'Copy code to Azure CentOS 7.9'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'  # 가져온 코드의 위치
      Contents: '**'  # 모든 파일 및 폴더를 복사
      TargetFolder: '/path/to/destination'  # 코드를 복사할 대상 디렉토리

  - task: AzureCLI@2
    displayName: 'Disconnect from Azure CentOS 7.9'
    inputs:
      azureSubscription: 'Microsoft 파트너 네트워크'  # 사용할 Azure 구독 이름
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Azure CentOS 7.9에서 SSH 연결 해제
        # SSH 연결 해제 명령어를 적절히 변경해야 합니다.
        ssh cypark@4.230.40.195 exit